const games=[
  {
    id:"0",
    title:"Covid-19",
    titleImage:"img/covid-19/covid19-title.jpg",
    description:"Ihr befindet Euch im Studentenzimmer, des Medizinstudenten, Holger. Dieser bereiste während seines Studiums, desöfteren in Länder, Afrika und Asien. Dort besorgte er sich den Impfstoff, gegen Covid-19. Auf diesen Impfstoff habt ihr es auch abgesehen und daher habt ihr nun 60 Minuten Zeit, im Studentenzimmer, nach dem Impfstoff, zu suchen. Viel Erfolg!",
    shortDescription: "Ein Medizinstudent versteckt in seinem Zimmer den Impfstoff gegen Covid-19. Seid ihr neugierig ????",
	  isPasswordProtected: false,
    password: "",
    hints:[],
    builtOrBought: 'Selbst gebaut in ca. 6 Wochen',
    availableSince: 'Seit 14.06.2020',
    difficulty: '1,5 von 5 Sternen',
    duration: '60 Minuten (bisher zwischen 53 und 80 Minuten) Bestzeit: 53:12 Minuten am 07.05.2022',
    roomSize: 'Ca. 20m² auf der Dachterasse (Outdoor)',
    playerSize: 'Ideal 2 bis 3 Personen (kann aber auch gut alleine gespielt werden)',
    playable: 'April bis Oktober, oder auch an besonders guten Tagen (auf Terasse)',
    specialFeatures: 'Ein 1.0 Raum mit Zahlenschlösser (ideal für Neueinsteger)',
    ideaOrigin: 'Als leidenschaftlicher Escape-Room Spieler, war ich im ersten Lockdown gefangen und hatte zu viel Langeweile. Daher dachte ich mir, baust dir einen Raum selber ;-) Dieser kam bei Freunden und Bekannten gut an :-)',
    additionalImages: [
      "img/covid-19/covid19-1.jpg"
    ]
  },
  {
    id:"1",
    title:"Das Fussballspiel (nur auf Anfrage spielbar)",
    titleImage:"img/fussballspiel/1.jpg",
    description:"Ihr seid Fussballfans vom FC St. Pauli und am Wochenende steht das Derby, gegen den Hamburger SV, an. Da euch euer Verein sehr am Herzen liegt, möchtet ihr eurer Mannschaft, im Vorfeld, helfen. Dafür habt ihr 90 Minuten Zeit, um im Vereinsheim, des Hamburger SV, irgendwas nützliches zu finden, um das Spiel dann erfolgreich zu gestalten. Alles Gute :-)",
    shortDescription: "Der Raum ist nicht nur was für Fussballfans, sondern kann von jedem gespielt werden. Es lohnt sich auf jeden Fall",
    isPasswordProtected: false,
    password: "",
    hints:[],
    builtOrBought: 'Selbst gebaut (im 1/2 Jahr)',
    availableSince: 'Seit 06. Dezember 2020',
    difficulty: '3 von 5 Sternen',
    duration: '90 Minuten plus Verlängerung ;-) Rekord: 92:12 Minuten am 25.08.2024',
    roomSize: 'Ca. 20m² auf der Dachterasse (Outdoor)',
    playable: 'Nur noch auf besonderer Anfrage (Mai bis September)',
    specialFeatures: 'Ein Raum der nicht nur was für Fussballfans ist, sondern auch ohne Fussballverstand gespielt werden kann. Diesmal gibt es sogar Magnetschlösser ;-)',
    ideaOrigin: 'Nach dem gelungenen ersten Raum, dachte ich mir sofort, da musst du noch was machen. Hatte tolle Ideen für Magnetschlösser und bin auch Fussballfan, daher dieser Raum ;-)',
    additionalImages: []
  },
  {
    id:"2",
    title:"Die Erbschaft Kains",
    titleImage:"img/erbschaft-kains/title.jpg",
    description:"Gutsherr Markus-Theodor Kains ist verstorben. Er war als Geschäftsführer, der Jung Berghoff Log GmbH (JBL), tätig und als Weinliebhaber, viel in Europa unterwegs. Da er aber nicht sehr beliebt war, streitet sich jetzt die Familie um die Erbschaft. Daher hat er den Angehörigen, viele Rätsel und Hindernisse in den Weg gestellt, damit man nicht so leicht an die Erbschaft kommt. Nachdem ihr nun Zugang zu dem Gutshof bekommen habt, möchtet ihr gerne an ein Teil vom Erbe gelangen. Viel Erfolg :-)",
    shortDescription: "Ihr müsst auf dem Gutshof, der Familie Kains, nach Hinweisen suchen, um sämtliche Rätel lösen zu können. Außerdem ist die Familienchronik zu sortieren und Produkte aus der Jung Berghoff Log GmbH zuzuordnen, um dann an die Erbschaft zu gelangen. Viel Erfolg :-)",
    isPasswordProtected: false,
    password: "",
    hints:[],
    builtOrBought: 'Selbst gebaut (Bauphase betrug 708 Tage)',
    availableSince: '02. Januar 2023',
    difficulty: '4 von 5 Sternen',
    duration: 'Gut 2 Stunden könnten es werden ;-)',
    roomSize: '12,61 m² (Indoor)',
    playable: 'Ganzjährig (bevorzugt am Wochenende)',
    specialFeatures: 'Dieser Raum ist mit Rätseln und Schlössern überhäuft, also genau das Richtige, für Tüftler und Rätselfreunde',
    ideaOrigin: 'Nach zwei Räumen auf der Dachterasse, die nur von April bis Oktober, spielbar sind, musste unbedingt drinnen ein Raum geschaffen werden',
    additionalImages: []
  },
  {
    id:"3",
    title:"Das Geheimnis von Professor T. (Rätselbox)",
    titleImage:"img/ratzellbox/title.jpg",
    description:"In einer kleinen Stadt, lebte eins der berühmte Professor T., ein weltbekannter Abenteurer und Gelehrter, der für seine faszinierden Reisen bekannt war. Sein ganzes Leben hatte er unerforschte Länder bereist, Kulturen entdeckt und Schätze gesammelt. Doch eines Tages, nach einer Reise, kehrte er nicht zurück. Die Stadt war in Aufruhr, und das Gerücht machte die Runde, dass er ein großes Geheimnis entdeckt hatte, bevor er spurlos verschwand. Könnt ihr helfen ??????",
	  shortDescription: "Hier handelt es sich um eine geheimnisvolle Rätselkiste, welche auch zu Hause gespielt werden kann.",
	  isPasswordProtected: true,
	  password: "123456",
    hints:[
      {text:"Sieh dir das Schloss mal genauer an. Vielleicht findest du da eine Ähnlichkeit gegenüber anderer Sachen.", image:"img/ratzellbox/hinweis_1.jpg"},
      {text:"Das Schloss und das Emblem auf dem Deckel sind doch Baugleich.",image:"img/ratzellbox/hinweis_2.jpg"},
      {text:"Achte auf die Reihenfolge der Farben.",image:"img/ratzellbox/hinweis_3.jpg"},
      {text:"Verbinde nun die Muster.",image:"img/ratzellbox/hinweis_4.jpg"},
      {text:"Die Summe der Hinweise ergibt die Lösung.",image:"img/ratzellbox/hinweis_5.jpg"}
    ],
    builtOrBought: 'Selbst gebaut (in der Winterzeit, in ca. 10 Wochen)',
    availableSince: '01. Januar 2025',
    duration: 'Zwischen 75 und 90 Minuten',
    playable: 'Jederzeit ;-) ',
    specialFeatures: 'Die Rätselkiste kann man sich auch zu sich nach Hause holen und dann kann dort gerätselt werden',
    ideaOrigin: 'Das ich keine Räumlichkeiten mehr zur Verfügung hatte, aber noch reichlich Ideen im Kopf, dachte ich mir, so eine Rätselkiste hätte was ;-)',
    additionalImages: []
  }
];
